### PR TITLE
Fix inline diff bug

### PR DESCRIPTION
**Pull request by j2gl**
1. Fixes bug of inline diff, and also added some unit tests.
2. Add some documentation

```
java.lang.ArrayIndexOutOfBoundsException: 1

    at difflib.DiffRowGenerator.copyEqualsLines(DiffRowGenerator.java:418)
    at difflib.DiffRowGenerator.generateDiffRows(DiffRowGenerator.java:387)
    at difflib.DiffRowGenerator.generateDiffRows(DiffRowGenerator.java:281)
    at diffutils.DiffRowGeneratorTest.testGenerator_InlineDiff(DiffRowGeneratorTest.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:252)
    at junit.framework.TestSuite.run(TestSuite.java:247)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

[EQUAL,anything,anything]
[EQUAL,,]
[EQUAL,other,other]
[CHANGE,more lines,some more lines]
[CHANGE,anything ,anything]
[CHANGE, ,]
[EQUAL,other,other]
```

### CODE REVIEW

**Comment by bkromhout** [comment]
Hi, I'm so sorry I haven't gotten around to looking at this yet. I'm hoping to find some spare time soon. It does look good preliminarily, I'd just like to verify everything myself and check the language a bit. Thanks so much for doing this though!

**Comment by bkromhout** [comment]
Great job here @j2gl! I'll merge this and then probably touch up the documentation a little bit. I really appreciate this.

**Comment by j2gl** [comment]
Thanks @bkromhout!

Maybe you can activate the option to report issues in this repo,  I'm doing some work with the library, so maybe I'll add more PR.  

Thanks for merging.

j2gl

**Comment by bkromhout** [comment]
Done, thanks!

**Pull request merged**
